-- 1. Find the Student details and Placement details using NATURAL JOIN.
-- 2. Find all the student details with company_name who have conducted in same drive
-- 3. List all the Student name and Student branch of Student having package 5 LPA
-- 4.List all the student names ,company_name having T_fee more than 20000
-- 5. Display all training details attended by “shantanu” in year 2011
-- 6. list the total number of companies who conduct training before 2015
-- 7. List the students name with company ‘Microsoft’ and location ’Thane’
-- 8. Find the names of all Students who have joined ‘Microsoft ‘ training in 2015 .
-- 9. Create a view showing the Student and Training details.
-- 10. Perform Manipulation on simple view-Insert, update, delete, drop view.
